@startuml system_architecture

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User", "A user of RecipeBank")
Person(admin, "Admin", "System administrator")

System_Boundary(app, "RecipeBank") {
    Container(web_ui, "Web UI", "Go Templ+HTMX", "Web application")
    Container(core_api, "Core API", "Go", "Implements all application logic and data operations")
    Container(auth_service, "Authentication Service", "Go", "Manages user authentication")
}

SystemDb_Ext(db, "Database", "Stores recipes and user data")
System_Ext(reverse_proxy, "Reverse Proxy", "TLS termination and load balancing")
System_Ext(prometheus, "Prometheus", "Metrics collection")
System_Ext(grafana, "Grafana", "Metrics visualization")

Rel_D(user, reverse_proxy, "Uses", "HTTPS")
BiRel_D(reverse_proxy, web_ui, "Forwards requests", "HTTP")
BiRel_D(reverse_proxy, core_api, "Forwards API requests", "HTTP")
BiRel_R(web_ui, core_api, "Makes API calls")
BiRel_D(core_api, auth_service, "Authenticates requests")
BiRel_D(core_api, db, "Reads from and writes to")
BiRel_D(auth_service, db, "Verifies credentials")

Rel(app, prometheus, "Exposes metrics")

Rel(prometheus, grafana, "Provides metrics")

Rel(admin, grafana, "Monitors")
Rel(admin, db, "Handles users")

@enduml
