name: Generate PlantUML Diagrams

on:
  push:
    paths:
      - '**.puml'

permissions:
  contents: write

jobs:
  generate-plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate PlantUML Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tpng **.puml

      - name: Commit and push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update generated PlantUML diagrams
          file_pattern: 'docs/*.png'
          branch: main
